# Generated by Django 5.0.6 on 2024-09-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='progreso',
            field=models.IntegerField(default=0),
        ),
    ]
