# Generated by Django 5.0.2 on 2025-03-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_progreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='progreso',
        ),
        migrations.AddField(
            model_name='profile',
            name='progreso_autoestima',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='progreso_logros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='progreso_personalidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='progreso_valores',
            field=models.IntegerField(default=0),
        ),
    ]
