# Generated by Django 5.0.2 on 2025-03-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_progreso_presentacionsegundopaso_profile_progreso_presentacionsegundopaso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='progreso_infografiatercerpaso',
            field=models.IntegerField(default=0),
        ),
    ]
