# Generated by Django 5.0.2 on 2025-03-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_progreso_infografiatercerpaso'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='progreso_presentaciontercerpaso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='progreso_tablerotercerpaso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='progreso_videoconsejotercerpaso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='progreso_videotercerpaso',
            field=models.IntegerField(default=0),
        ),
    ]
