# Generated by Django 5.0.2 on 2025-03-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_progreso_presentaciontercerpaso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='progreso_agendacuartopaso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='progreso_tablerocuartopaso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='progreso_videocuartopaso',
            field=models.IntegerField(default=0),
        ),
    ]
