# Generated by Django 5.0.2 on 2025-03-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_progreso_agendacuartopaso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='progreso_imagenquintopaso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='progreso_infografiaquintopaso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='progreso_tableroquintopaso',
            field=models.IntegerField(default=0),
        ),
    ]
