# Generated by Django 5.0.2 on 2025-03-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_progreso_imagenquintopaso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='progreso_tablerosextopaso',
            field=models.IntegerField(default=0),
        ),
    ]
