# Generated by Django 5.0.2 on 2025-03-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_progreso_tablerosextopaso'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='progreso_formatoseptimopaso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='progreso_fraseseptimopaso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='progreso_imagen2septimopaso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='progreso_imagenseptimopaso',
            field=models.IntegerField(default=0),
        ),
    ]
