# Generated by Django 5.0.2 on 2025-03-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_progreso_formatoseptimopaso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='progreso_formato2septimopaso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='progreso_infografiaseptimopaso',
            field=models.IntegerField(default=0),
        ),
    ]
