# Generated by Django 5.0.2 on 2025-03-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_progreso_formato2septimopaso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.CharField(max_length=30),
        ),
    ]
