# Generated by Django 5.0.2 on 2025-03-03 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_telefono'),
        ('users', '0016_meta'),
    ]

    operations = [
    ]
