# Generated by Django 5.1.2 on 2025-03-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_constancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_tutor',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
