version: "3"

services:
  api:
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "3401:8000"
    restart: always
    volumes:
      - sqlite-container:/app/db
      - constancias:/app/media/constancias
    ## command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000" # Elimina o comenta esta línea

volumes:
  sqlite-container:
    driver: local
  constancias:
    driver: local
