# Generated by Django 5.0.2 on 2025-02-02 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inteligencia_verbal', models.IntegerField(default=0)),
                ('inteligencia_logica', models.IntegerField(default=0)),
                ('inteligencia_visual', models.IntegerField(default=0)),
                ('inteligencia_corporal', models.IntegerField(default=0)),
                ('inteligencia_musical', models.IntegerField(default=0)),
                ('inteligencia_intrapersonal', models.IntegerField(default=0)),
                ('inteligencia_interpersonal', models.IntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
