name: Deploy TuCarrera App (Docker Compose)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS with Docker Compose
      uses: alex-ac/github-action-ssh-docker-compose@master
      with:
        ssh_host: ${{ secrets.SSH_HOST }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.SSH_USER }}
        ssh_port: ${{ secrets.SSH_PORT || 22 }}
        docker_compose_prefix: tucarrera
        docker_compose_filename: docker-compose.yml
