name: Docker CI/CD

on:
  push:
    branches: [ "main" ] # Cambia "main" por tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t tucarrera-app-image .

    - name: Log in to Docker Hub (opcional)
      # Si quieres subir la imagen a Docker Hub, configura las credenciales como secretos
      # uses: docker/login-action@v2
      # with:
      #   username: ${{ secrets.DOCKERHUB_USERNAME }}
      #   password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the Docker image to Docker Hub (opcional)
      # Si iniciaste sesión en Docker Hub, puedes subir la imagen
      # run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tucarrera-app-image:latest

    - name: Deployment to VPS (Próximo paso)
      run: echo "Simulando despliegue a VPS en el siguiente paso..."
